SET SQL_SAFE_UPDATES = 0;
SELECT * from USUARIOS;

DELETE FROM USUARIOS WHERE name = "Astro";

CREATE TABLE IF NOT EXISTS USUARIOS (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL DEFAULT "NORMAL"
)